# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('fecha', models.DateTimeField()),
                ('cuenta', models.CharField(max_length=50, verbose_name='Cuenta')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
