# Generated by Django 2.1.7 on 2019-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_auto_20180405_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoIgnorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('string', models.CharField(max_length=200, verbose_name='String')),
                ('regex', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Descripción')),
                ('codigo', models.CharField(max_length=200, verbose_name='Código')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
