# Generated by Django 2.1.7 on 2019-04-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0006_categoria_regex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='regex',
            new_name='search_str',
        ),
    ]
